version: "#{build}"
pull_requests:
  do_not_increment_build_number: true
configuration:
  - Release
clone_depth: 5
before_build:
  - cmd: call .appveyor\appveyor_helper.bat
build_script:
  - cmd: call "%VS90COMNTOOLS%vsvars32.bat"
  - cmd: vcbuild win_configure\pbs_windows_VS2008.sln "Release|Win32"
after_build:
  - cmd: call .appveyor\generate_installer.bat
test: off
deploy: off

