language: c
sudo: required
group: deprecated-2017Q2
services:
    - docker
env:
    - OS_TYPE=centos:7
    - OS_TYPE=opensuse
    - OS_TYPE=debian:8
before_install:
    - .github/runchecks
    - docker pull ${OS_TYPE}
    - docker run -it -d -h testdev.pbspro.com --name testdev -v `pwd`:`pwd` --privileged -w `pwd` ${OS_TYPE} /bin/sh
    - docker ps -a
    - export DOCKER_EXEC_TTY="docker exec -it testdev"
    - export DOCKER_EXEC="docker exec -i testdev"
    - export DOCKER_TESTDEV_IP="$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' testdev)"
    - ${DOCKER_EXEC} /bin/sh -c "echo '${DOCKER_TESTDEV_IP}     testdev' >> /etc/hosts"
    - ${DOCKER_EXEC} cat /etc/hosts
install:
    - ./.travis/${OS_TYPE//:/_}.sh
script: true

