language: c
sudo: required
group: deprecated-2017Q2
services:
    - docker
env:
    - OS_TYPE=centos:7
    - OS_TYPE=opensuse
before_install:
    - .github/runchecks
    - docker pull ${OS_TYPE}
    - docker run -it -d -h testdev.pbspro.com --name testdev -v `pwd`:`pwd` --privileged -w `pwd` ${OS_TYPE} /bin/bash
    - docker ps -a
    - export DOCKER_EXEC="docker exec -it testdev"
    - export DOCKER_TESTDEV_IP="$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' testdev)"
    - ${DOCKER_EXEC} /bin/bash -c "echo '${DOCKER_TESTDEV_IP}     testdev' >> /etc/hosts"
    - ${DOCKER_EXEC} cat /etc/hosts
install:
    - travis_retry ./.travis/${OS_TYPE//:/_}.sh
    - ${DOCKER_EXEC} /bin/bash -c "cd test/fw; pip install -r requirements.txt ."
    - ${DOCKER_EXEC} pbs_config --make-ug
    - ${DOCKER_EXEC} /bin/bash -c "cd test/tests; pbs_benchpress -l INFOCLI2 -o ../../ptl.txt"
script: true

